config/routes.rb
ChipotleApp::Application.routes.draw do

  # Before switching to 'resouces'
  # root 'users#new'

  # get '/users' => 'users#index'
  # get 'sign_up' => 'users#new', as: "sign_up"
  # post '/users' => 'users#create'

  # get '/orders' => 'orders#index'
  # post '/orders' => 'orders#create'
  # get '/orders/new' => 'orders#new'
  # get '/orders/:id/edit' => 'orders#edit', as: :edit_order
  # patch '/orders/:id' => 'orders#update', as: :order
  # delete '/orders/:id' => 'orders#destroy'

  # Swapped out
  # get '/users/new' => 'users#new'
  # get '/orders/:id' => 'orders#show'

  resources :orders, only: [:index, :show, :create, :new, :edit, :update, :destroy]
  resources :users, only: [:index, :create, :new]
  resource :auth, only: [:create]

  get 'sign_in' => 'auths#new', as: 'login'
  delete 'sign_out' => 'auths#destroy', as: 'logout'

  root to: 'orders#index'

end

app/models/order.rb
class Order
  include Mongoid::Document
  field :type, type: String
  field :meat, type: Array, default: []
  field :cheese, type: Mongoid::Boolean

  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document

  attr_accessor :password

  field :username, type: String
  field :password_salt, type: String
  field :password_hash, type: String
  has_many :orders

  # validates_confirmation_of :password
  # validates_presence_of :password, :on => :create
  # validates_presence_of :username
  # validates_uniqueness_of :username

  def authenticated?(passwd)
    # self.password_hash == BCrypt::Engine.hash_secret(passwd, self.password_salt)
    BCrypt::Password.new(self.password_hash) == passwd
  end

  before_save :encrypt_password
  
  private
    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        self.password = nil
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end
  
  def login_required
    unless current_user
      flash[:error] = "You must be logged in to do that!"
      redirect_to root_path
    end
  end
  
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user.authenticated?(params[:user][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{current_user.username}!"
      redirect_to orders_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to orders_path
  end
end

app/controllers/concerns/auths_controller.rb
class AuthsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(name: params[:user][:name])
    if user.authenticates_with_password?(params[:user][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{current_user.name}!"
      redirect_to orders_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :login_required, only: [:destroy]

  def index
    @orders = Order.all
    # if params[:show] == "completed"
    #   @orders = Order.where(is_completed: true)
    # elsif params[:show] == "all"
    #   @orders = Order.all
    # else
    #   @orders = Order.where(is_completed: false)
    # end
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to action: 'index'
      flash[:notice] = "Successfully submitted order!"
    else
      render action: 'new'
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to action: 'index'
      flash[:notice] = 'Order was successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to action: 'index'
  end

  private
  def order_params
    params.require(:order).permit(:type, :cheese, meat: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :password))
    if @user.save
      # redirect_to orders_new_path
      redirect_to root_path
    else
      render "new"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/new.html.erb
<%= form_for @user, url: auth_path, method: 'post' do |f| %>
  <%= f.text_field :username, placeholder: 'Enter name' %><br />
  <%= f.password_field :password, placeholder: 'Enter password' %><br />
  <%= f.submit 'Log in' %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if current_user %>
  Logged in as <%= current_user.username %> | 
  <%= link_to 'Log out', logout_path, method: 'delete' %>
<% else %>
  <%= link_to 'Log in', login_path %> |
  <%= link_to 'Sign up', new_user_path %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chipotle App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <p style="color: tomato; font-size: 16px" class="notice"><%= flash[:notice] %></p>
  <p class="error"><%= flash[:error] %></p>
  
  <%= yield %>

  <br><br><hr><%= current_user %>

</body>
</html>

app/views/orders/edit.html.erb
<h1>Ughh you need to change your order?</h1>

<%= form_for @order do |f| %>
  <div>
    <%= f.label :type %>:
    <%= f.select :type, ['Burrito', 'Taco', 'Quesadilla', 'Salad Bowl'] %>
  </div>

  <div>
    <%= f.label :meat %>
    <%= check_box_tag 'order[meat][]', 'chicken', @order.meat.include?('chicken') %>
    <%= check_box_tag 'order[meat][]', 'steak', @order.meat.include?('steak') %>
    <%= check_box_tag 'order[meat][]', 'tofu', @order.meat.include?('tofu') %>
  </div>
  
  <div>
    <%= f.label :cheese %>:
    <%= f.check_box :cheese %>Yes
  </div>

  <div><%= f.submit %></div>

<% end %>

app/views/orders/index.html.erb
<!--
ToDo:
1. Require partial
2. Add authentication
3. Add custom paramters
4. Style with Boostrap
-->

<h2>Order Queue</h2>
<table>
<tr>
  <th>User</th>
  <th>Type</th>
  <th>Meat</th>
  <th>Cheese</th>
  <th>Edit?</th>
  <th>Cancel?</th>
</tr>
<% @orders.each do |order| %>
<tr>
  <td><%= current_user ? current_user.username : "Log in!" %></td>
  <td><%= order.type %></td>
  <td><%= order.meat %></td>
  <td><%= order.cheese %></td>
  <td><%= link_to 'Edit', edit_order_path(order) %></td>
  <td><%= link_to 'Cancel', order, method: :delete, data: { confirm: 'Are you sure?'} %></td>
</tr>
<% end %>
</table>

app/views/orders/new.html.erb
<h2>What would you like?</h2>

<%= form_for @order do |f| %>
  <div>
    <b><%= f.label :type %></b>:
    <%= f.select :type, ['Burrito', 'Taco', 'Quesadilla', 'Salad Bowl'] %>
  </div>

  <div>
    <b><%= f.label :meat %></b>:
    <%= check_box_tag 'order[meat][]', 'chicken', @order.meat.include?('chicken') %>Chicken
    <%= check_box_tag 'order[meat][]', 'steak', @order.meat.include?('steak') %>Steak
    <%= check_box_tag 'order[meat][]', 'tofu', @order.meat.include?('tofu') %>Tofu
  </div>
  
  <div>
    <b><%= f.label :cheese %>?</b>:
    <%= f.check_box :cheese %>Yes
  </div>
  <br>
  <div><%= f.submit %></div>

<% end %>

app/views/orders/show.html.erb
<h1>Test</h1>

app/views/users/index.html.erb
<h1>List of all Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% if current_user %>
  Whoa Nelly! You're already logged in!
  <br>
  Click here to go to the order form.
<% else %>
  <h2>Sign up to order your derricious Chipotle burrito!</h2>
  <%= form_for @user do |f| %>
    <%= f.text_field :username, placeholder: "Enter your name" %><br>
    <%= f.password_field :password, placeholder: "Enter a password" %><br>
    <%#= f.password_field :password_confirmation, placeholder: "Confirm password" %><br>
  <%= f.submit "CreeEaAaAte New User" %>
  <% end %>
<% end %>